"""
DEMO PRODUCT DATASET FOR FINOPT PROTOTYPE

DISCLAIMER:
Illustrative demo data for hackathon prototype.
All institution names, product titles, and interest rates are fictional.
They do not represent real-world bank offerings or current financial advice.
"""

from typing import List
from models import Product, ProductTenure

DEMO_PRODUCTS: List[Product] = [
    Product(
        id="prod_apex_01",
        institution="Apex Trust Bank (Demo)",
        product_name="Apex Secure Term Deposit",
        category="Fixed Deposit",
        minimum_amount=5000.0,
        maximum_amount=20000000.0,
        liquidity_level="balanced",
        conditions="Premature withdrawal allowed with standard 0.5% penalty. Loan against FD available up to 90%.",
        source="Illustrative demo data for hackathon prototype",
        last_updated="2026-09-01",
        tenures=[
            ProductTenure(id="pt_apex_6m", product_id="prod_apex_01", tenure_months=6, annual_interest_rate=6.25, compounding_frequency=4),
            ProductTenure(id="pt_apex_9m", product_id="prod_apex_01", tenure_months=9, annual_interest_rate=6.60, compounding_frequency=4),
            ProductTenure(id="pt_apex_12m", product_id="prod_apex_01", tenure_months=12, annual_interest_rate=7.10, compounding_frequency=4),
            ProductTenure(id="pt_apex_15m", product_id="prod_apex_01", tenure_months=15, annual_interest_rate=7.45, compounding_frequency=4),
            ProductTenure(id="pt_apex_18m", product_id="prod_apex_01", tenure_months=18, annual_interest_rate=7.60, compounding_frequency=4),
            ProductTenure(id="pt_apex_24m", product_id="prod_apex_01", tenure_months=24, annual_interest_rate=7.30, compounding_frequency=4),
            ProductTenure(id="pt_apex_36m", product_id="prod_apex_01", tenure_months=36, annual_interest_rate=7.00, compounding_frequency=4),
        ],
    ),
    Product(
        id="prod_beacon_02",
        institution="Beacon Small Finance Bank (Demo)",
        product_name="Beacon High-Yield Term Deposit",
        category="Fixed Deposit",
        minimum_amount=10000.0,
        maximum_amount=5000000.0,
        liquidity_level="low",
        conditions="Strict lock-in for full term. 1.0% penalty on early closure. Higher returns for disciplined savers.",
        source="Illustrative demo data for hackathon prototype",
        last_updated="2026-09-01",
        tenures=[
            ProductTenure(id="pt_beacon_9m", product_id="prod_beacon_02", tenure_months=9, annual_interest_rate=6.90, compounding_frequency=4),
            ProductTenure(id="pt_beacon_12m", product_id="prod_beacon_02", tenure_months=12, annual_interest_rate=7.50, compounding_frequency=4),
            ProductTenure(id="pt_beacon_15m", product_id="prod_beacon_02", tenure_months=15, annual_interest_rate=7.95, compounding_frequency=4),
            ProductTenure(id="pt_beacon_18m", product_id="prod_beacon_02", tenure_months=18, annual_interest_rate=8.10, compounding_frequency=4),
            ProductTenure(id="pt_beacon_24m", product_id="prod_beacon_02", tenure_months=24, annual_interest_rate=7.80, compounding_frequency=4),
        ],
    ),
    Product(
        id="prod_crestline_03",
        institution="Crestline Digital Bank (Demo)",
        product_name="Crestline Flexi-Liquid FD",
        category="Fixed Deposit",
        minimum_amount=1000.0,
        maximum_amount=10000000.0,
        liquidity_level="high",
        conditions="Zero penalty for premature withdrawal after 30 days. Monthly compounding credit.",
        source="Illustrative demo data for hackathon prototype",
        last_updated="2026-09-01",
        tenures=[
            ProductTenure(id="pt_crest_6m", product_id="prod_crestline_03", tenure_months=6, annual_interest_rate=6.00, compounding_frequency=12),
            ProductTenure(id="pt_crest_9m", product_id="prod_crestline_03", tenure_months=9, annual_interest_rate=6.40, compounding_frequency=12),
            ProductTenure(id="pt_crest_12m", product_id="prod_crestline_03", tenure_months=12, annual_interest_rate=6.85, compounding_frequency=12),
            ProductTenure(id="pt_crest_15m", product_id="prod_crestline_03", tenure_months=15, annual_interest_rate=7.05, compounding_frequency=12),
            ProductTenure(id="pt_crest_18m", product_id="prod_crestline_03", tenure_months=18, annual_interest_rate=7.20, compounding_frequency=12),
            ProductTenure(id="pt_crest_24m", product_id="prod_crestline_03", tenure_months=24, annual_interest_rate=7.10, compounding_frequency=12),
        ],
    ),
    Product(
        id="prod_delta_04",
        institution="Delta Commercial Bank (Demo)",
        product_name="Delta Sovereign Growth Deposit",
        category="Fixed Deposit",
        minimum_amount=25000.0,
        maximum_amount=50000000.0,
        liquidity_level="balanced",
        conditions="Backed by AAA-equivalent safety rating. Quarterly compounding. Premature withdrawal at 0.75% penalty.",
        source="Illustrative demo data for hackathon prototype",
        last_updated="2026-09-01",
        tenures=[
            ProductTenure(id="pt_delta_6m", product_id="prod_delta_04", tenure_months=6, annual_interest_rate=6.15, compounding_frequency=4),
            ProductTenure(id="pt_delta_12m", product_id="prod_delta_04", tenure_months=12, annual_interest_rate=7.00, compounding_frequency=4),
            ProductTenure(id="pt_delta_18m", product_id="prod_delta_04", tenure_months=18, annual_interest_rate=7.35, compounding_frequency=4),
            ProductTenure(id="pt_delta_24m", product_id="prod_delta_04", tenure_months=24, annual_interest_rate=7.25, compounding_frequency=4),
            ProductTenure(id="pt_delta_36m", product_id="prod_delta_04", tenure_months=36, annual_interest_rate=7.15, compounding_frequency=4),
        ],
    ),
    Product(
        id="prod_evergreen_05",
        institution="Evergreen Co-operative Bank (Demo)",
        product_name="Evergreen Community Safe Deposit",
        category="Fixed Deposit",
        minimum_amount=2000.0,
        maximum_amount=2500000.0,
        liquidity_level="balanced",
        conditions="Focus on local safe deposits. Annual compounding for short tenures, quarterly for 12m+.",
        source="Illustrative demo data for hackathon prototype",
        last_updated="2026-09-01",
        tenures=[
            ProductTenure(id="pt_ever_6m", product_id="prod_evergreen_05", tenure_months=6, annual_interest_rate=6.30, compounding_frequency=2),
            ProductTenure(id="pt_ever_12m", product_id="prod_evergreen_05", tenure_months=12, annual_interest_rate=7.15, compounding_frequency=4),
            ProductTenure(id="pt_ever_15m", product_id="prod_evergreen_05", tenure_months=15, annual_interest_rate=7.50, compounding_frequency=4),
            ProductTenure(id="pt_ever_24m", product_id="prod_evergreen_05", tenure_months=24, annual_interest_rate=7.40, compounding_frequency=4),
            ProductTenure(id="pt_ever_36m", product_id="prod_evergreen_05", tenure_months=36, annual_interest_rate=7.20, compounding_frequency=4),
        ],
    ),
    Product(
        id="prod_fortress_06",
        institution="Fortress Micro-Finance Bank (Demo)",
        product_name="Fortress Stepped Yield Deposit",
        category="Fixed Deposit",
        minimum_amount=10000.0,
        maximum_amount=3000000.0,
        liquidity_level="low",
        conditions="High returns for 15-18m 'sweet spot' tenures. Penalty of 1.25% if closed before 12 months.",
        source="Illustrative demo data for hackathon prototype",
        last_updated="2026-09-01",
        tenures=[
            ProductTenure(id="pt_fort_9m", product_id="prod_fortress_06", tenure_months=9, annual_interest_rate=6.80, compounding_frequency=4),
            ProductTenure(id="pt_fort_12m", product_id="prod_fortress_06", tenure_months=12, annual_interest_rate=7.40, compounding_frequency=4),
            ProductTenure(id="pt_fort_15m", product_id="prod_fortress_06", tenure_months=15, annual_interest_rate=8.00, compounding_frequency=4),
            ProductTenure(id="pt_fort_18m", product_id="prod_fortress_06", tenure_months=18, annual_interest_rate=8.20, compounding_frequency=4),
            ProductTenure(id="pt_fort_24m", product_id="prod_fortress_06", tenure_months=24, annual_interest_rate=7.75, compounding_frequency=4),
        ],
    ),
    Product(
        id="prod_gateway_07",
        institution="Gateway Merchant Bank (Demo)",
        product_name="Gateway Instant-Liquidity FD",
        category="Fixed Deposit",
        minimum_amount=50000.0,
        maximum_amount=10000000.0,
        liquidity_level="high",
        conditions="Full liquidity with partial withdrawal option without breaking deposit. Monthly compounding.",
        source="Illustrative demo data for hackathon prototype",
        last_updated="2026-09-01",
        tenures=[
            ProductTenure(id="pt_gate_6m", product_id="prod_gateway_07", tenure_months=6, annual_interest_rate=6.10, compounding_frequency=12),
            ProductTenure(id="pt_gate_9m", product_id="prod_gateway_07", tenure_months=9, annual_interest_rate=6.55, compounding_frequency=12),
            ProductTenure(id="pt_gate_12m", product_id="prod_gateway_07", tenure_months=12, annual_interest_rate=6.95, compounding_frequency=12),
            ProductTenure(id="pt_gate_15m", product_id="prod_gateway_07", tenure_months=15, annual_interest_rate=7.15, compounding_frequency=12),
            ProductTenure(id="pt_gate_24m", product_id="prod_gateway_07", tenure_months=24, annual_interest_rate=7.05, compounding_frequency=12),
        ],
    ),
    Product(
        id="prod_heritage_08",
        institution="Heritage National Bank (Demo)",
        product_name="Heritage Premier Term Deposit",
        category="Fixed Deposit",
        minimum_amount=10000.0,
        maximum_amount=100000000.0,
        liquidity_level="balanced",
        conditions="Large institutional safety pedigree. Quarterly compounding. Senior citizen extra 0.5% (base rate shown).",
        source="Illustrative demo data for hackathon prototype",
        last_updated="2026-09-01",
        tenures=[
            ProductTenure(id="pt_heri_6m", product_id="prod_heritage_08", tenure_months=6, annual_interest_rate=6.00, compounding_frequency=4),
            ProductTenure(id="pt_heri_12m", product_id="prod_heritage_08", tenure_months=12, annual_interest_rate=6.90, compounding_frequency=4),
            ProductTenure(id="pt_heri_18m", product_id="prod_heritage_08", tenure_months=18, annual_interest_rate=7.20, compounding_frequency=4),
            ProductTenure(id="pt_heri_24m", product_id="prod_heritage_08", tenure_months=24, annual_interest_rate=7.10, compounding_frequency=4),
            ProductTenure(id="pt_heri_36m", product_id="prod_heritage_08", tenure_months=36, annual_interest_rate=6.80, compounding_frequency=4),
        ],
    ),
    Product(
        id="prod_imperial_09",
        institution="Imperial Capital Bank (Demo)",
        product_name="Imperial Milestone Growth FD",
        category="Fixed Deposit",
        minimum_amount=20000.0,
        maximum_amount=15000000.0,
        liquidity_level="balanced",
        conditions="Optimized for 12 to 18 month terms with step-up interest. Quarterly compounding.",
        source="Illustrative demo data for hackathon prototype",
        last_updated="2026-09-01",
        tenures=[
            ProductTenure(id="pt_imp_9m", product_id="prod_imperial_09", tenure_months=9, annual_interest_rate=6.70, compounding_frequency=4),
            ProductTenure(id="pt_imp_12m", product_id="prod_imperial_09", tenure_months=12, annual_interest_rate=7.20, compounding_frequency=4),
            ProductTenure(id="pt_imp_15m", product_id="prod_imperial_09", tenure_months=15, annual_interest_rate=7.65, compounding_frequency=4),
            ProductTenure(id="pt_imp_18m", product_id="prod_imperial_09", tenure_months=18, annual_interest_rate=7.75, compounding_frequency=4),
            ProductTenure(id="pt_imp_36m", product_id="prod_imperial_09", tenure_months=36, annual_interest_rate=7.10, compounding_frequency=4),
        ],
    ),
    Product(
        id="prod_zenith_10",
        institution="Zenith Wealth Bank (Demo)",
        product_name="Zenith Advantage Term Deposit",
        category="Fixed Deposit",
        minimum_amount=100000.0,
        maximum_amount=50000000.0,
        liquidity_level="balanced",
        conditions="Designed for deposits of ₹1,00,000 and above. Quarterly compounding with premium rate tier.",
        source="Illustrative demo data for hackathon prototype",
        last_updated="2026-09-01",
        tenures=[
            ProductTenure(id="pt_zen_6m", product_id="prod_zenith_10", tenure_months=6, annual_interest_rate=6.40, compounding_frequency=4),
            ProductTenure(id="pt_zen_9m", product_id="prod_zenith_10", tenure_months=9, annual_interest_rate=6.80, compounding_frequency=4),
            ProductTenure(id="pt_zen_12m", product_id="prod_zenith_10", tenure_months=12, annual_interest_rate=7.35, compounding_frequency=4),
            ProductTenure(id="pt_zen_15m", product_id="prod_zenith_10", tenure_months=15, annual_interest_rate=7.70, compounding_frequency=4),
            ProductTenure(id="pt_zen_18m", product_id="prod_zenith_10", tenure_months=18, annual_interest_rate=7.85, compounding_frequency=4),
            ProductTenure(id="pt_zen_24m", product_id="prod_zenith_10", tenure_months=24, annual_interest_rate=7.50, compounding_frequency=4),
        ],
    ),
]


def get_all_products() -> List[Product]:
    """Retrieve all available demo products (simulating repository / database query)."""
    return DEMO_PRODUCTS
